name: Build and Publish

on:
  push:
    branches:
      - main
#    tags:
#      - '.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      run: |-
        pip install poetry==1.8.3
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |-
        poetry install --only main --no-root

    - name: Build package
      run: |-
        poetry build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-dist
        path: dist/

  publish-to-pypi:
    name: >-
      Publish dist to PyPI
#    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gcp-compute-machines
    permissions:
      id-token: write

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/
      - name: Publish dist to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1